### ISSUE TITLE
Switch from `ini` config file to use generic anyconfig library.

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/populus#151]
### What was wrong?

`ini` configuratino files are not great.  Lets switch the project configuration over to `yaml`.  While doing that, lets write a `populus.config.Config` object that fully wraps the underlying configuration so that we aren't married to the file format.

``` yaml
version: 1
project:
  base_dir: /path/to/project
chains:
  mainnet:
    provider: web3.providers.ipc.IPCProvider
  morden:
    port: 12345
```
